import Disc from "./types.js";

const discs: Disc[] = [
  {
    id: 1,
    name: "Bridges to Babylon",
    artistName: "The Rolling Stones",
    imageUrl: "images/disc1.webp",
    type: "Vinyl",
    price: 18.99,
    originalPrice: 21.99,
    isDiscOfTheMonth: true,
  },
  {
    id: 2,
    name: "Sueño su boca",
    artistName: "Raúl",
    imageUrl: "images/disc2.webp",
    type: "Vinyl",
    price: 99.99,
    originalPrice: 119.99,
    isDiscOfTheMonth: false,
  },
  {
    id: 3,
    name: "Temple of the Dog",
    artistName: "Temple of the Dog",
    imageUrl: "images/disc3.webp",
    type: "Digital",
    price: 23.99,
    originalPrice: 23.99,
    isDiscOfTheMonth: false,
  },

  {
    id: 4,
    name: "Whenever you need somebody",
    artistName: "Rick Astley",
    imageUrl: "images/disc4.webp",
    type: "Digital",
    price: 269.99,
    originalPrice: 359.99,
    isDiscOfTheMonth: false,
  },
  {
    id: 5,
    name: "Marifé de Triana",
    artistName: "Marifé de Triana",
    imageUrl: "images/disc5.webp",
    type: "Vinyl",
    price: 219.99,
    originalPrice: 219.99,
    isDiscOfTheMonth: false,
  },
  {
    id: 6,
    name: "Show me love",
    artistName: "Robin S",
    imageUrl: "images/disc6.webp",
    type: "Digital",
    price: 19.99,
    originalPrice: 19.99,
    isDiscOfTheMonth: false,
  },
  {
    id: 7,
    name: "Homework",
    artistName: "Daft Punk",
    imageUrl: "images/disc7.webp",
    type: "Vinyl",
    price: 24.59,
    originalPrice: 24.59,
    isDiscOfTheMonth: false,
  },
  {
    id: 8,
    name: "El Chiringuito",
    artistName: "Georgie Dann",
    imageUrl: "images/disc8.webp",
    type: "Vinyl",
    price: 1.99,
    originalPrice: 1.99,
    isDiscOfTheMonth: true,
  },
];

export default discs;
